### ISSUE TITLE
error occur during train with salsanext_mos without pretrained  model

### ISSUE THREAD

**Issue by LiXiang0021** [PRBonn/LiDAR-MOS#48] opened 2022-04-04 14:11 UTC
Thanks for author's remarkable working!

when i start to train this network without pretrained model, this error occurs showing below.
Can someone help me, thanks a lot!

/home/lijianguo/anaconda3/envs/LiDAR-MOS-1.1/bin/python /media/lijianguo/data_ssd/coding_test_platfrom/LiDAR-MOS-1.1/mos_SalsaNext/train/tasks/semantic/train.py -d /media/lijianguo/data_ssd/coding_test_platfrom/LiDAR-MOS-1.1/data -ac /media/lijianguo/data_ssd/coding_test_platfrom/LiDAR-MOS-1.1/mos_SalsaNext/salsanext_mos.yml -l /media/lijianguo/data_ssd/coding_test_platfrom/LiDAR-MOS-1.1/data/train_logs
Opening arch config file /media/lijianguo/data_ssd/coding_test_platfrom/LiDAR-MOS-1.1/mos_SalsaNext/salsanext_mos.yml
Opening data config file config/labels/semantic-kitti-mos.yaml

INTERFACE:
dataset /media/lijianguo/data_ssd/coding_test_platfrom/LiDAR-MOS-1.1/data
arch_cfg /media/lijianguo/data_ssd/coding_test_platfrom/LiDAR-MOS-1.1/mos_SalsaNext/salsanext_mos.yml
data_cfg config/labels/semantic-kitti-mos.yaml
uncertainty True
Total of Trainable Parameters: 6.71M
log /media/lijianguo/data_ssd/coding_test_platfrom/LiDAR-MOS-1.1/data/train_logs/logs/2022-4-04-22:06
pretrained None

Traceback (most recent call last):
  File "/media/lijianguo/data_ssd/coding_test_platfrom/LiDAR-MOS-1.1/mos_SalsaNext/train/tasks/semantic/train.py", line 136, in <module>
    os.makedirs(FLAGS.log)
  File "/home/lijianguo/anaconda3/envs/LiDAR-MOS-1.1/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 22] Invalid argument: '/media/lijianguo/data_ssd/coding_test_platfrom/LiDAR-MOS-1.1/data/train_logs/logs/2022-4-04-22:06'

**Comment by Chen-Xieyuanli** [comment] 2022-04-04 14:36
Hey @LiXiang0021, thanks for using our code!

It seems that the log path is invalid. You may double-check the file/folder names to be readable by python.

**Comment by LiXiang0021** [comment] 2022-04-05 02:49
Thanks for your answer, doctor Chen!
It works.

**Comment by Chen-Xieyuanli** [comment] 2022-04-05 06:15
@LiXiang0021, I'm happy it works for you! I would appreciate it if you could star our repo to let more people see it.

Since the issue is solved, I would like to close it. Please feel free to contact me if you find any other problems.

**Closed by Chen-Xieyuanli** 2022-04-05 06:15 UTC

**Comment by LiXiang0021** [comment] 2022-04-10 04:39
Thanks for your quick response!
@Chen-Xieyuanli 

I trained with salsa_mos in semantic kitti. When it run here 
`Lr: 3.977e-03 | Update: 3.258e-04 mean,5.209e-04 std | Epoch: [0][950/2391] | Time 0.641 (0.623) | Data 0.081 (0.067) | Loss 0.6863 (0.9777) | acc 0.830 (0.855) | IoU 0.417 (0.434) | [1 day, 3:19:41]`
`LiDAR-MOS/mos_SalsaNext/train/tasks/semantic/../../common/laserscan.py:166: RuntimeWarning: invalid value encountered in true_divide
  pitch = np.arcsin(scan_z / depth)`
 i got error
`File "conda/envs/salsa/lib/python3.9/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 1.`
and 
` File "LiDAR-MOS/mos_SalsaNext/train/tasks/semantic/../../common/laserscan.py", line 201, in do_range_projection
    self.proj_range[proj_y, proj_x] = depth
IndexError: index -2147483648 is out of bounds for axis 0 with size 64`
The conda env is 
`- python=3.9.12=h12debd9_0
  - python-flatbuffers=1.12=pyhd3eb1b0_0
  - pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - tensorflow-base=2.6.0=mkl_py39h3d85931_0
  - tensorflow-estimator=2.6.0=pyh7b7c402_0`
  Is there any wrong with this env？or it is too new?
